# Generated by Django 4.2.1 on 2023-05-17 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='quantity',
        ),
        migrations.AddField(
            model_name='sales',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='sales',
            name='items',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reciepts',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='store',
            name='expiry',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='store',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trash',
            name='expiry',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
