# Generated by Django 4.2.1 on 2023-05-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_sales_medicine_remove_sales_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
