# Generated by Django 4.2.1 on 2023-05-23 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_sales_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='items',
        ),
    ]
