# Generated by Django 4.2.1 on 2023-05-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_sales_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='items',
            field=models.JSONField(blank=True, max_length=1000, null=True),
        ),
    ]
