# Generated by Django 4.2.1 on 2023-05-23 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_sales_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
