# Generated by Django 4.2.1 on 2023-05-29 06:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_store_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='worker',
        ),
        migrations.AlterField(
            model_name='reciepts',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
