# Generated by Django 4.1.3 on 2023-06-08 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_store_worker_alter_reciepts_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciepts',
            name='image',
        ),
    ]
